version: '3.8'

services:
  web:
    build: .
    container_name: login-web
    volumes:
      - ./html:/var/www/html
      - ./css:/var/www/css
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8084:80
    depends_on:
      - db
      - mailhog


  db:
    image: mysql:8.0
    container_name: login-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: logindb
      MYSQL_USER: user
      MYSQL_PASSWORD: root1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./html:/var/www/html
      - ./css:/var/www/html/css
    ports:
      - 3307:3306
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"